name: background_services
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <3.86.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  health:
  permission_handler:
  firebase_core: 
  google_sign_in: 
  pedometer:
  flutter_local_notifications:
  firebase_messaging:
  firebase_analytics:
  firebase_auth:
  shared_preferences:
  cloud_firestore:
  awesome_notifications:
  rxdart:
  flutter_foreground_task:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: 
  flutter_native_splash: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
